//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artmin_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int ArtistID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string BankAccountNo { get; set; }
        public int EventID { get; set; }
    
        public virtual Event Events { get; set; }
    }
}
